---
image:
  name: docker

stages:
  - build
  - push

before_scripts:
  - docker login --username ${DOCKERHUB_USERNAME} --password ${DOCKERHUB_PASSWORD}

build_image:
  stage: build
  script:
    - sudo docker build -t mcanevet/terraform:latest .

push_image:
  stage: push
  script:
    - docker push mcanevet/terraform:latest
