name: Docker repo update

on:
  workflow_dispatch:

jobs:
  update-repo:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Update APT package index
      run: sudo apt update

    - name: Install jq
      run: sudo apt install jq

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.dockerhub_username }}
        password: ${{ secrets.dockerhub_password }}

    - name: Execute script
      run: ./update.sh
      env:
        uname: ${{ secrets.dockerhub_username }}
        upass: ${{ secrets.dockerhub_password }}
        dest_repo: ${{ secrets.dockerhub_repo }}
