name: Docker repo update

on:
  # Manual trigger used the first time to populate the destination repo, comment once repo up-to-date
  workflow_dispatch:

  # Daily workflow executions
  # Uncomment schedule block once repo up-to-date
  #schedule:
  #- cron: '0 0 * * *'

jobs:
  update-repo:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Update APT package index
      run: sudo apt update

    - name: Install jq
      run: sudo apt install jq

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.username }}
        password: ${{ secrets.token }}

    - name: Execute script
      run: ./update.sh
      env:
        github_pat: ${{ secrets.token }}
