name: Github container repo update

on:
  workflow_dispatch:

  # Daily workflow executions
  schedule:
  - cron: '0 0 * * *'

jobs:
  update-repo:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Update APT package index
      run: sudo apt update

    - name: Install jq
      run: sudo apt install jq

    - name: Login to registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Execute script
      run: ./update.sh
      env:
        github_pat: ${{ secrets.GITHUB_TOKEN }}
